### PR TITLE
boost parsing performance with parallel parsing support

### PR DESCRIPTION
**Pull request by AlexKovalevych**

### CODE REVIEW

**Comment by AlexKovalevych** [comment]
This is a big change to general approach of parsing excel files. 
It extracts zip into memory, writes directly to ets tables avoiding sending messages to agents. On application start it creates a single state worker which is a parent for all ets tables..

According to my benchmark on the same ~12 Mb excel file:

was: 2:40m
now: 22s

**Comment by AlexKovalevych** [comment]
#49

**Comment by kennellroxco** [comment]
Hey @AlexKovalevych thanks for all the work on this. My apologies for the delay in replying, I've been trying to wrap up my busy season at work. I plan to pull down and review your pull request soon. I'll let you know if any questions come up.

**Comment by jsonkennell** [comment]
@AlexKovalevych there are a few issues we need to look into before I can merge this pull request: 

- While your changes greatly increased performance during the actual parsing of the file, it decreased the performance of the `get_list()` function. This is, of course, to be expected for the most part since you moved the generation of the `nil` cells to `get_list()`, there are situations where it becomes unusable. For example, in the test file (`./test/test_data/test.xlsx`) the worksheet at index 2 seems to get hung up when calling `get_list()` after extraction when it only took a couple of seconds before. 

- There are situations where no `styles` or `shared_strings` are generated due to the formatting of the file. These situations currently throw an argument error. 

- Since a generic `:worksheet` ETS table is no longer generated when using `extract/3`, there doesn't seem to be a need for it anymore. Its purpose was to negate the need for using and keeping track of a `pid` when working in a single worksheet. 

- Documentation and testing needs to be updated to incorporate your changes. 

I'll keep testing to see if I can come up with anything else. Thanks again for all the work you put into this!

**Comment by AlexKovalevych** [comment]
@jsonkennell Thank you for your review. I'll work on the issues you found.

**Comment by AlexKovalevych** [comment]
@jsonkennell I've fixed filling cells with nils (it was infinite recursion in some cases), but could you give me an excel file example without styles or shared_strings (or maybe create such test) so i can reproduce the issue.

**Comment by jsonkennell** [comment]
@AlexKovalevych I just created a branch called `no-shared-strings` where I added an `.xlsx` file for you to reproduce the issue. `./test/test_data/no-shared-strings.xlsx`

**Comment by AlexKovalevych** [comment]
@jsonkennell i fixed the issues and updated documentation a bit, please let me know what else should be done to complete this PR (I didn't update the HTML documentation though, should I? )

**Comment by jsonkennell** [comment]
@AlexKovalevych no, don't worry about the HTML docs, I'll update that before I publish to hex. I have a couple other ideas I'd like to work on with this PR before we merge. I'll try to work through them and get you comments over the upcoming weekend.

**Pull request merged**
