### PR TITLE
fixes for some xlsx variants and repeatable streams

### PR DESCRIPTION
**Pull request by rhetzler**
2 issues:
1) Some xlsx files do not contain sharedStrings.xml per ideas like this: http://ericwhite.com/blog/advice-when-generating-spreadsheets-use-inline-strings-not-shared-strings/

2) Since the %Stream{} resource is being initialized with references to files that have been pre-unpacked, re-running the stream after GC will reliably fail. A Quick consolidation (perhaps some refactoring would be good here) of initialization into the %Stream{} constructor means file unpacking is lazy and will re-run successfully after gc from the first run.

You can reproduce both issues by running the tests without the associated fixes they are checked in with.

Thanks!

### CODE REVIEW

**Comment by jsonkennell** [comment]
Thanks for the PR!

**Comment by Tricote** [comment]
Hey wanted to comment but didn't had the time before the merge. The fix works, but it doesn't looks like its related to the GC, but to the fact that the the `XlsxFile.clean/1` method is called at the end of the enumeration (cf: https://github.com/jsonkennell/xlsxir/blob/master/lib/xlsxir/xlsx_file.ex#L170). This method deletes shared_strings and styles ets tables so the stream cannot run a second time... 

Anyway this works (maybe there is a GC issue too, but I'm no expert...) :). Note that removing the call to `XlsxFile.clean/1` also fix the tests, but in that case the ets tables are not deleted at the end... So I suppose its ok to do it that way, knowing re-runnning the stream will extract again the xlsx files and ets tables each time

**Comment by rhetzler** [comment]
Hi @Tricote thanks for the comment!

By "GC" i meant the stream garbage collection of memory/ets and filesystem contents, which occurs in XlsxFile.clean/1 as you pointed out. ( https://github.com/jsonkennell/xlsxir/blob/master/lib/xlsxir/xlsx_file.ex#L104-L107 ). I don't see any problem with the GC. Just pointing out that when it runs, the stream could not be re-run, therefore i would have had to re-create the stream for each re-run, which would cause re-extract anyway (?)

With the 3 goals (in order of priority) of:
1. prevent ets/fs leaks ( don't want to remove call to XlsxFile.clean )
2. enable re-run ( result of this PR )
3. avoid multiple extracts ( unsatisfied, as you comment )

Maybe 3 would be a future PR, if there's a reasonable way to do it

**Comment by Tricote** [comment]
Ok thanks for your explanations!

 I was wondering if running the extraction inside a genserver would help doing 3... and do some better cleanup, cause a related issue is that there is currently some "filesystem leaks" for instance when the parsing crash, the temp files are left on the fs. When processing big files, this can be a real issue

Anyway, as you said, for a future PR

**Pull request merged**
