### PR TITLE
test for complex values in sharedStrings, changes to pass tests

### PR DESCRIPTION
**Pull request by brushbox**
Possible fix for issue #56 .

There are a few possible discussion points for this PR:

* I've removed some code which I didn't fully understand - the fix wanted to do the same thing in all cases so it seemed redundant to have two branches that did the same.
  * all the tests pass, so either this is good - or there are some more tests that may be needed.
  * the `%ParseString` struct could possibly be simplified due to these changes.
* I added a test at the `Xlsxir` level - which got me started. But then I added a test that specifically detailed the issue and is more focussed.
  * I'm not sure the outer test adds anything (I'm more than happy to remove it).
  * the narrower test is working directly with XML - I hope this is OK (I didn't see any other tests doing this).
* should the version number be incremented?

### CODE REVIEW

**Comment by jsonkennell** [comment]
@brushbox I didn't see this before commenting on #56. Thanks for working on a solution. I'll take a look to make sure this doesn't cause an issue in an area where we may need some additional tests.

**Comment by brushbox** [comment]
@jsonkennell I've updated this branch with the latest from master and made the changes to get it working again.

**Comment by brushbox** [comment]
I'm now in a position to check #58 and will do so shortly (based on this branch). I'll update that issue, if necessary, but I expect that the changes made will address them. Cheers!

**Comment by jsonkennell** [comment]
Thanks @brushbox , I'll try to spend some time on this over the holiday weekend.

**Pull request merged**
